name: Hello GitHub Actions

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show Git version
        run: git --version

      - name: Show repository
        run: 'echo Repository: $GITHUB_REPOSITORY'

      - name: Show branch
        run: 'echo Branch: $GITHUB_REF_NAME'

      - name: List files
        run: ls -la
